---
version: '3.4'
services:
  postgres:
    build:
      context: postgres
    image: postgres:mgarciate
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nasachallenge
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:7.2.1
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/etc/grafana/provisioning
    env_file:
      - ./grafana/config.monitoring
    restart: unless-stopped

volumes:
  postgres_data: {}
  grafana_data: {}